# Generated by Django 6.0.6 on 2026-06-12 07:55

import django.core.validators
import django_ckeditor_5.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_module', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productbrand',
            options={'verbose_name': 'برند', 'verbose_name_plural': 'برندها'},
        ),
        migrations.AlterModelOptions(
            name='productcategory',
            options={'verbose_name': 'دسته\u200cبندی', 'verbose_name_plural': 'دسته\u200cبندی\u200cها'},
        ),
        migrations.AlterModelOptions(
            name='producttag',
            options={'verbose_name': 'تگ محصول', 'verbose_name_plural': 'تگ\u200cهای محصولات'},
        ),
        migrations.AddField(
            model_name='product',
            name='active_ingredient',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='ماده موثره (فرمولاسیون)'),
        ),
        migrations.AddField(
            model_name='product',
            name='complementary_safety_gears',
            field=models.ManyToManyField(blank=True, to='product_module.product', verbose_name='تجهیزات ایمنی/مکمل پیشنهادی'),
        ),
        migrations.AddField(
            model_name='product',
            name='dosage_farm',
            field=models.FloatField(blank=True, null=True, verbose_name='دوز مصرف زراعت (در هکتار)'),
        ),
        migrations.AddField(
            model_name='product',
            name='dosage_greenhouse',
            field=models.FloatField(blank=True, null=True, verbose_name='دوز مصرف گلخانه (در هکتار)'),
        ),
        migrations.AddField(
            model_name='product',
            name='dosage_orchard',
            field=models.FloatField(blank=True, null=True, verbose_name='دوز مصرف باغات (در هکتار)'),
        ),
        migrations.AddField(
            model_name='product',
            name='inventory',
            field=models.PositiveIntegerField(default=0, verbose_name='موجودی انبار (تعداد)'),
        ),
        migrations.AddField(
            model_name='product',
            name='max_postal_qty',
            field=models.PositiveIntegerField(default=5, help_text='اگر کاربر بیشتر از این تعداد سفارش داد، کل سبد به اجبار با باربری ارسال می\u200cشود.', verbose_name='حداکثر تعداد مجاز برای پست'),
        ),
        migrations.AddField(
            model_name='product',
            name='msds_file',
            field=models.FileField(blank=True, null=True, upload_to='msds_files/', validators=[django.core.validators.FileExtensionValidator(['pdf'])], verbose_name='فایل اطلاعات ایمنی (MSDS)'),
        ),
        migrations.AddField(
            model_name='product',
            name='phi_days',
            field=models.PositiveIntegerField(blank=True, help_text='تعداد روزهای ماندگاری سم تا زمان برداشت', null=True, verbose_name='دوره کارنس (روز)'),
        ),
        migrations.AddField(
            model_name='product',
            name='shipping_class',
            field=models.CharField(choices=[('post', 'قابل ارسال با پست'), ('freight', 'فقط ارسال با باربری (حجم بالا / خطرناک)')], default='post', max_length=20, verbose_name='کلاس ارسال'),
        ),
        migrations.AddField(
            model_name='product',
            name='technical_description',
            field=django_ckeditor_5.fields.CKEditor5Field(blank=True, null=True, verbose_name='توضیحات فنی'),
        ),
        migrations.AddField(
            model_name='product',
            name='usage_timing',
            field=models.TextField(blank=True, null=True, verbose_name='نحوه و بهترین زمان مصرف'),
        ),
        migrations.AddField(
            model_name='product',
            name='weight_unit',
            field=models.CharField(choices=[('g', 'گرم'), ('kg', 'کیلوگرم'), ('cc', 'سی\u200cسی'), ('l', 'لیتر'), ('pcs', 'عدد')], default='l', max_length=10, verbose_name='واحد اندازه گیری'),
        ),
        migrations.AddField(
            model_name='product',
            name='weight_value',
            field=models.FloatField(default=0, help_text='مثال: 1.5 یا 500', verbose_name='مقدار وزن/حجم'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.ManyToManyField(related_name='product_categories', to='product_module.productcategory', verbose_name='دسته\u200cبندی\u200cها'),
        ),
        migrations.AlterField(
            model_name='product',
            name='description',
            field=django_ckeditor_5.fields.CKEditor5Field(verbose_name='توضیحات اصلی و معرفی'),
        ),
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images/products', verbose_name='تصویر اصلی محصول'),
        ),
        migrations.AlterField(
            model_name='product',
            name='is_delete',
            field=models.BooleanField(default=False, verbose_name='حذف شده / نشده'),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.IntegerField(verbose_name='قیمت (تومان)'),
        ),
        migrations.AlterField(
            model_name='product',
            name='short_description',
            field=models.CharField(db_index=True, max_length=360, null=True, verbose_name='توضیحات کوتاه (کارت محصول)'),
        ),
        migrations.AlterField(
            model_name='producttag',
            name='caption',
            field=models.CharField(db_index=True, max_length=300, verbose_name='عنوان تگ'),
        ),
        migrations.AlterField(
            model_name='productvisit',
            name='ip',
            field=models.CharField(max_length=30, verbose_name='آی\u200cپی کاربر'),
        ),
    ]
