# Generated by Django 6.0.6 on 2026-06-12 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_module', '0002_alter_productbrand_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='productcategory',
            name='color',
            field=models.CharField(default='#2563eb', help_text='مثال: #2563eb (آبی) یا #10b981 (سبز)', max_length=20, verbose_name='رنگ پس\u200cزمینه (کد هگز)'),
        ),
        migrations.AddField(
            model_name='productcategory',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images/categories', verbose_name='تصویر دسته\u200cبندی'),
        ),
    ]
