# Generated by Django 6.0.6 on 2026-06-12 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_module', '0003_productcategory_color_productcategory_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='productcategory',
            name='show_in_home',
            field=models.BooleanField(default=False, help_text='اگر فعال باشد، این دسته\u200cبندی در صفحه اصلی نمایش داده می\u200cشود', verbose_name='نمایش در صفحه اصلی'),
        ),
    ]
