# Generated by Django 6.0.6 on 2026-06-12 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_module', '0004_productcategory_show_in_home'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='discount_percent',
            field=models.PositiveIntegerField(default=0, help_text='برای نمایش تگ قرمز رنگ درصد تخفیف', verbose_name='درصد تخفیف'),
        ),
        migrations.AddField(
            model_name='product',
            name='hazard_class',
            field=models.CharField(blank=True, choices=[('red', 'بسیار خطرناک (نوار قرمز)'), ('yellow', 'خطرناک (نوار زرد)'), ('blue', 'خطر متوسط (نوار آبی)'), ('green', 'کم خطر (نوار سبز)')], max_length=20, null=True, verbose_name='کلاس خطر سموم'),
        ),
        migrations.AddField(
            model_name='product',
            name='is_wholesale',
            field=models.BooleanField(default=False, help_text='با فعال کردن این گزینه، تگ آبی رنگ "عمده" روی محصول نمایش داده می\u200cشود.', verbose_name='فروش عمده (همکار/کشاورز)'),
        ),
    ]
