# Generated by Django 6.0.6 on 2026-06-19 22:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order_module', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='address',
            field=models.TextField(blank=True, null=True, verbose_name='آدرس دقیق'),
        ),
        migrations.AddField(
            model_name='order',
            name='city',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='شهر'),
        ),
        migrations.AddField(
            model_name='order',
            name='first_name',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='نام گیرنده'),
        ),
        migrations.AddField(
            model_name='order',
            name='last_name',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='نام خانوادگی گیرنده'),
        ),
        migrations.AddField(
            model_name='order',
            name='mobile',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='شماره موبایل گیرنده'),
        ),
        migrations.AddField(
            model_name='order',
            name='payment_ref_number',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='شماره پیگیری پرداخت (refNumber)'),
        ),
        migrations.AddField(
            model_name='order',
            name='payment_track_id',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='شناسه پرداخت زیبال (trackId)'),
        ),
        migrations.AddField(
            model_name='order',
            name='postal_code',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='کد پستی'),
        ),
        migrations.AddField(
            model_name='order',
            name='province',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='استان'),
        ),
        migrations.AddField(
            model_name='order',
            name='shipping_cost',
            field=models.IntegerField(default=0, verbose_name='هزینه ارسال'),
        ),
        migrations.AddField(
            model_name='order',
            name='shipping_method',
            field=models.CharField(blank=True, choices=[('post', 'پست پیشتاز'), ('barbari', 'ارسال با باربری (پس\u200cکرایه)')], max_length=20, null=True, verbose_name='روش ارسال'),
        ),
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('pending', 'در انتظار پرداخت'), ('processing', 'در حال پردازش'), ('shipped', 'ارسال شده'), ('delivered', 'تحویل شده'), ('canceled', 'لغو شده')], default='pending', max_length=20, verbose_name='وضعیت سفارش'),
        ),
        migrations.AddField(
            model_name='order',
            name='tracking_code',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='کد رهگیری ارسال'),
        ),
        migrations.AlterField(
            model_name='order',
            name='is_paid',
            field=models.BooleanField(default=False, verbose_name='نهایی شده/نشده'),
        ),
        migrations.AlterField(
            model_name='order',
            name='payment_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='تاریخ پرداخت'),
        ),
    ]
