# Generated by Django 6.0.6 on 2026-06-12 15:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AdminAlertNumber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='نام مدیر')),
                ('phone_number', models.CharField(max_length=11, verbose_name='شماره موبایل')),
                ('receive_daily_reports', models.BooleanField(default=True, verbose_name='دریافت گزارش روزانه')),
                ('receive_low_credit_alerts', models.BooleanField(default=True, verbose_name='دریافت هشدار اتمام شارژ')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
            ],
            options={
                'verbose_name': 'شماره ادمین (هشدارها)',
                'verbose_name_plural': 'شماره\u200cهای ادمین (هشدارها)',
            },
        ),
        migrations.CreateModel(
            name='SMSConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('api_key', models.CharField(max_length=255, verbose_name='کلید API (X-API-KEY)')),
                ('low_credit_threshold', models.DecimalField(decimal_places=0, default=100000, max_digits=12, verbose_name='آستانه هشدار شارژ (تومان)')),
                ('is_active', models.BooleanField(default=True, help_text='برای قطع اضطراری کل پیامک\u200cهای سایت', verbose_name='سیستم پیامکی فعال باشد؟')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='آخرین بروزرسانی')),
            ],
            options={
                'verbose_name': 'تنظیمات درگاه پیامک',
                'verbose_name_plural': 'تنظیمات درگاه پیامک',
            },
        ),
        migrations.CreateModel(
            name='SMSLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(help_text='مثلا: 30004505000017', max_length=20, unique=True, verbose_name='شماره خط')),
                ('title', models.CharField(help_text='مثلا: خط اطلاع\u200cرسانی', max_length=100, verbose_name='عنوان خط')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
                ('is_default_for_bulk', models.BooleanField(default=False, verbose_name='خط پیش\u200cفرض ارسال گروهی')),
                ('is_default_for_p2p', models.BooleanField(default=False, verbose_name='خط پیش\u200cفرض ارسال نظیر به نظیر')),
            ],
            options={
                'verbose_name': 'خط پیامکی',
                'verbose_name_plural': 'خطوط پیامکی',
            },
        ),
        migrations.CreateModel(
            name='SMSTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('internal_name', models.CharField(help_text='نام ثابت در کد مثل OTP_LOGIN', max_length=100, unique=True, verbose_name='نام سیستمی قالب')),
                ('template_id', models.IntegerField(help_text='شناسه عددی قالب', verbose_name='کد قالب در sms.ir')),
                ('body_preview', models.TextField(help_text='مثلا: کد ورود شما #Code# می\u200cباشد.', verbose_name='پیش\u200cنمایش متن قالب')),
                ('required_parameters', models.JSONField(default=list, help_text='مثال: ["Code", "Name"]', verbose_name='متغیرهای اجباری')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
            ],
            options={
                'verbose_name': 'قالب خدماتی (Verify)',
                'verbose_name_plural': 'قالب\u200cهای خدماتی',
            },
        ),
        migrations.CreateModel(
            name='ScheduledPack',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pack_id', models.CharField(blank=True, max_length=100, null=True, unique=True, verbose_name='شناسه بسته (sms.ir)')),
                ('total_recipients', models.IntegerField(default=0, verbose_name='تعداد مخاطبین')),
                ('total_cost', models.DecimalField(decimal_places=0, default=0, max_digits=10, verbose_name='هزینه کل (تومان)')),
                ('scheduled_datetime', models.DateTimeField(blank=True, null=True, verbose_name='زمان مقرر برای ارسال')),
                ('status', models.CharField(choices=[('PENDING', 'در انتظار ارسال'), ('SENT', 'ارسال شده'), ('CANCELED', 'لغو شده'), ('FAILED', 'خطا در سامانه')], default='PENDING', max_length=20, verbose_name='وضعیت بسته')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('line', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='sms_module.smsline', verbose_name='خط ارسالی')),
            ],
            options={
                'verbose_name': 'بسته پیامک زمان\u200cبندی شده',
                'verbose_name_plural': 'بسته\u200cهای پیامک زمان\u200cبندی شده',
            },
        ),
        migrations.CreateModel(
            name='InboundSMSLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('receive_id', models.BigIntegerField(unique=True, verbose_name='شناسه دریافت (sms.ir)')),
                ('sender_mobile', models.CharField(max_length=15, verbose_name='شماره فرستنده')),
                ('message_text', models.TextField(verbose_name='متن پیامک')),
                ('received_at', models.DateTimeField(verbose_name='زمان دریافت (از سامانه)')),
                ('is_processed', models.BooleanField(default=False, verbose_name='پردازش شده توسط سیستم؟')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ثبت در سایت')),
                ('line', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='sms_module.smsline', verbose_name='خط دریافت\u200cکننده')),
            ],
            options={
                'verbose_name': 'پیامک دریافتی',
                'verbose_name_plural': 'پیامک\u200cهای دریافتی',
                'ordering': ['-received_at'],
            },
        ),
        migrations.CreateModel(
            name='OutboundSMSLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message_id', models.BigIntegerField(blank=True, null=True, unique=True, verbose_name='شناسه پیامک (sms.ir)')),
                ('mobile', models.CharField(max_length=15, verbose_name='شماره مقصد')),
                ('message_text', models.TextField(verbose_name='متن پیامک')),
                ('cost', models.DecimalField(blank=True, decimal_places=0, max_digits=8, null=True, verbose_name='هزینه (تومان)')),
                ('send_type', models.CharField(choices=[('VERIFY', 'خدماتی (Verify)'), ('BULK', 'گروهی (Bulk)'), ('P2P', 'نظیر به نظیر (P2P)')], max_length=10, verbose_name='نوع ارسال')),
                ('delivery_state', models.IntegerField(blank=True, choices=[(1, 'رسیده به گوشی'), (2, 'نرسیده به گوشی'), (3, 'رسیده به مخابرات'), (4, 'نرسیده به مخابرات'), (5, 'رسیده به اپراتور'), (6, 'ناموفق'), (7, 'لیست سیاه'), (8, 'نامشخص')], null=True, verbose_name='وضعیت دلیوری')),
                ('delivery_datetime', models.DateTimeField(blank=True, null=True, verbose_name='زمان دلیوری')),
                ('sent_at', models.DateTimeField(auto_now_add=True, verbose_name='زمان ارسال')),
                ('pack', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='sms_module.scheduledpack', verbose_name='بسته مرتبط')),
                ('line', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='sms_module.smsline', verbose_name='خط ارسال\u200cکننده')),
                ('template', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='sms_module.smstemplate', verbose_name='قالب استفاده شده')),
            ],
            options={
                'verbose_name': 'تاریخچه ارسال',
                'verbose_name_plural': 'تاریخچه ارسال\u200cها',
                'ordering': ['-sent_at'],
            },
        ),
    ]
