# Generated by Django 6.0.6 on 2026-06-11 21:26

import django_ckeditor_5.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Slider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='عنوان اصلی')),
                ('badge_text', models.CharField(blank=True, max_length=50, null=True, verbose_name='متن تگ (مثلاً: تخفیف\u200cهای بهاره)')),
                ('description', django_ckeditor_5.fields.CKEditor5Field(verbose_name='توضیحات')),
                ('image', models.ImageField(upload_to='sliders/', verbose_name='تصویر اسلایدر')),
                ('btn1_text', models.CharField(blank=True, max_length=50, null=True, verbose_name='متن دکمه اول')),
                ('btn1_link', models.URLField(blank=True, null=True, verbose_name='لینک دکمه اول')),
                ('btn2_text', models.CharField(blank=True, max_length=50, null=True, verbose_name='متن دکمه دوم')),
                ('btn2_link', models.URLField(blank=True, null=True, verbose_name='لینک دکمه دوم')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال است؟')),
                ('order', models.IntegerField(default=0, verbose_name='ترتیب نمایش')),
            ],
            options={
                'verbose_name': 'اسلایدر',
                'verbose_name_plural': 'اسلایدرها',
                'ordering': ['order', '-id'],
            },
        ),
    ]
