# Generated by Django 6.0.6 on 2026-06-12 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AuthSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_otp_enabled', models.BooleanField(default=True, verbose_name='ورود/ثبت\u200cنام پیامکی فعال باشد؟')),
                ('is_password_enabled', models.BooleanField(default=True, verbose_name='ورود با رمز عبور فعال باشد؟')),
                ('force_profile_completion', models.BooleanField(default=True, verbose_name='اجبار به تکمیل پروفایل پس از ثبت\u200cنام؟')),
            ],
            options={
                'verbose_name': 'تنظیمات احراز هویت',
                'verbose_name_plural': 'تنظیمات احراز هویت',
            },
        ),
        migrations.CreateModel(
            name='OTPRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(db_index=True, max_length=15, verbose_name='شماره موبایل')),
                ('otp_code', models.CharField(max_length=128, verbose_name='کد تایید')),
                ('purpose', models.CharField(choices=[('LOGIN', 'ورود و ثبت\u200cنام'), ('CHANGE_PHONE', 'تغییر شماره موبایل'), ('TWO_FACTOR', 'احراز هویت دو مرحله\u200cای'), ('VERIFY_ACTION', 'تایید عملیات حساس')], default='LOGIN', max_length=20, verbose_name='هدف از ارسال')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='آی\u200cپی درخواست\u200cدهنده')),
                ('user_agent', models.TextField(blank=True, verbose_name='مشخصات دستگاه/مرورگر')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='زمان ایجاد')),
                ('expires_at', models.DateTimeField(verbose_name='زمان انقضا')),
                ('is_used', models.BooleanField(default=False, verbose_name='استفاده شده')),
                ('failed_attempts', models.PositiveSmallIntegerField(default=0, verbose_name='تعداد تلاش ناموفق')),
            ],
            options={
                'verbose_name': 'درخواست کد تایید',
                'verbose_name_plural': 'درخواست\u200cهای کد تایید',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['phone_number', 'created_at'], name='otp_auth_ot_phone_n_9aad65_idx'), models.Index(fields=['ip_address', 'created_at'], name='otp_auth_ot_ip_addr_38d423_idx')],
            },
        ),
    ]
