# Generated by Django 6.0.6 on 2026-06-19 20:52

import django_ckeditor_5.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article_module', '0001_initial'),
        ('product_module', '0005_product_discount_percent_product_hazard_class_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='related_articles',
            field=models.ManyToManyField(blank=True, to='article_module.article', verbose_name='مقالات مرتبط'),
        ),
        migrations.AddField(
            model_name='article',
            name='related_products',
            field=models.ManyToManyField(blank=True, to='product_module.product', verbose_name='محصولات مرتبط'),
        ),
        migrations.AlterField(
            model_name='article',
            name='text',
            field=django_ckeditor_5.fields.CKEditor5Field(verbose_name='متن مقاله'),
        ),
    ]
