# Generated by Django 6.0.6 on 2026-06-19 22:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account_module', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='email_active_code',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='کد فعالسازی ایمیل'),
        ),
    ]
