# Generated by Django 6.0.6 on 2026-06-19 22:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account_module', '0002_user_email_active_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='email_active_code',
            field=models.CharField(blank=True, default='', max_length=100, null=True, verbose_name='کد فعالسازی ایمیل'),
        ),
    ]
